### ISSUE TITLE
cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by deter3** [jm12138/iFLYTEK-MSC-Python-SDK#1]
Running on ubuntu 22 , python3.9.17 , install okay . when import msc , THE ERROR  . /root/.pyenv/versions/3.9.17/lib/python3.9/site-packages/msc/bin/msc_x64.so: cannot open shared object file: No such file or directory . 

Do you have fix ? thanks

**Comment by jm12138** [comment]
> Running on ubuntu 22 , python3.9.17 , install okay . when import msc , THE ERROR  . /root/.pyenv/versions/3.9.17/lib/python3.9/site-packages/msc/bin/msc_x64.so: cannot open shared object file: No such file or directory . 
> 
> Do you have fix ? thanks 
> 

The bug has been fixed. You need to manually download an official SDK, match it with the corresponding AppID, and use the latest version to use it normally.
